GET http://localhost:8080/api/v1/membrosDaFamilia

###

POST http://localhost:8080/api/v1/membrosDaFamilia
Content-Type: application/json

{
    "nome": "Maicon",
    "sexo": "masculino",
    "email": "maicon@maicon",
    "usuario": "maicon",
    "senha": "maicon"
}

###

GET http://localhost:8080/api/v1/membrosDaFamilia/3


###

PUT http://localhost:8080/api/v1/membrosDaFamilia/1
Content-Type: application/json

{
  "id": 3,
  "nome": "Maicon",
  "sexo": "masculino",
  "email": "maicon@maicon",
  "dataDeNascimento": null,
  "usuario": "maiconteste",
  "senha": "senhaalteradaviaapi"
}

###

DELETE http://localhost:8080/api/v1/membrosDaFamilia/

###

# @name loginAPI
POST http://localhost:8080/api/v1/auth/signin
Content-Type: application/json

{
  "usuario": "admin",
  "senha": "admin"
}

###
@token = {{loginAPI.response.body.*}}

###
GET http://localhost:8080/api/v1/membrosDaFamilia
Authorization: Bearer {{token}}
